spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
#    open-in-view: false

  #        show_sql: true #SQL문을 print로 출력
#        format_sql: true #SQL 문을 보기좋게 출력

  jackson:
    serialization:
      fail-on-empty-beans: false


#logging:
#  level:
#    org.hibernate.SQL: debug #SQL문을 logger로 출력
#    org.hibernate.type: trace #SQL parameter를 출력
